language: ruby
sudo: false
install:
  - ./script/travis_cache download_bundle
  - gem install bundler # use the very latest Bundler
  - bundle install --without development --path=./bundle
  - bundle clean # delete now-outdated gems
  - ./script/travis_cache download_app
  - bundle exec rake setup
  - ./script/travis_cache upload
script:
  - bundle exec rake test_with_coveralls
rvm:
  - 2.1.5
  - 2.2.3
  - jruby-9.0.1.0
gemfile:
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
env:
  global:
    - RAILS_V=$(bundle exec rails -v)
    - RAILS_VERSION="${RAILS_V##Rails }"
    # Need Fuzzy Version, so keep "D.D.", and add x
    - RAILS="${RAILS_V:0:3}x"
    - JRUBY_OPTS="-J-Xmx1024m --debug"
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#activeadmin
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
