language: ruby

rvm:
  - 1.9.3
  - 2.1

sudo: false

cache: bundler

before_script:
  - bundle exec rake setup

script:
  - bundle exec rake test_with_coveralls

env:
  matrix:
    - RAILS=3.2.20
    - RAILS=4.1.7
notifications:
  irc:
    channels:
      - "irc.freenode.org#activeadmin"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
