language: ruby
sudo: false
install:
  - gem install bundler # use the very latest Bundler
  - bundle install --without development --path=./bundle
  - bundle clean # delete now-outdated gems
  - bundle exec rake setup
script:
  - bundle exec rake test_with_coveralls
rvm:
  - 1.9
  - 2.3.0
  - jruby-9.0.5.0
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9
      gemfile: gemfiles/rails_5.gemfile
  allow_failures:
    - rvm: 2.3.0
      gemfile: gemfiles/rails_5.gemfile
    - rvm: jruby-9.0.5.0
      gemfile: gemfiles/rails_5.gemfile
notifications:
  irc:
    channels:
      - irc.freenode.org#activeadmin
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
