language: ruby
sudo: false
install:
  - gem install bundler # use the very latest Bundler
  - bundle exec rake setup
script:
  - bundle exec rake test_with_coveralls
rvm:
  - 1.9
  - 2.3.0
  - jruby-9.0.5.0
env:
  matrix:
    - RAILS=3.2.22
    - RAILS=4.2.5
    - RAILS="> 5.x"
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9
      env: RAILS="> 5.x"
  allow_failures:
    - rvm: 2.3.0
      env: RAILS="> 5.x"
    - rvm: jruby-9.0.5.0
      env: RAILS="> 5.x"
branches:
  only:
    - master
    - /\A\d-\d-stable\z/
notifications:
  irc:
    channels:
      - irc.freenode.org#activeadmin
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
