before_script:
  - bundle exec rake setup
script:
  - bundle exec rspec
  - RAILS_ENV=cucumber bundle exec cucumber --profile default
  - RAILS_ENV=cucumber bundle exec cucumber --profile class-reloading
rvm:
  - ree
  - 1.9.2
  - 1.9.3
before_install:
  - gem update --system
  - gem --version
env:
  - RAILS=3.0.12
  - RAILS=3.1.4
  - RAILS=3.2.3
