language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - spec/rails
bundler_args: --without development
before_script:
  - bundle exec rake setup
script:
  - bundle exec rake test_with_coveralls
rvm:
  - 1.9
  - 2.1
  - 2.2
  - jruby-9.0.0.0
env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: jruby-9.0.0.0
      gemfile: gemfiles/rails_3.2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_4.2.gemfile
env:
  global:
    - secure: lRYUGVUV94eqrR7C0b0hhvp+W76NkLRAn6jkJGCbRCEojbeb3HlgK1P+nTDeIuiDmXksJOG6VD3ZiZAn9Plznj7I/MFh+ijgvk8eWj9QNxA8riaSEPAu5VYtPA+uaw1olUt196U3qXH+SaXB4sx5wdIUXpd9qxWWWsW11ia0Jzs=
    - JRUBY_OPTS="-J-Xmx1024m --debug"
notifications:
  irc:
    channels:
      - "irc.freenode.org#activeadmin"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "(%{branch}/%{commit} by %{author}): %{message} (%{build_url})"
